.section .rodata

.include "include/beatscript.inc"


@ Prologue (Showtime) - Script
glabel script_showtime_prologue
    set_game_fade_in_time 8
    load_game showtime_prologue_engine, 0
    run stop_all_soundplayers, 0
    rest 24
    play_sfx s_jingle_quiz_seqData
    rest 24
    rest 24
    run func_08045a50, 5
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    run func_08006d80, 0
    rest 24
    set_game_fade_in_time 16
    return

.end
