.include "include/beatscript.inc"
.include "games/drum_studio/macros.inc"

load_drum_studio_labels



.section .rodata
@ Drum Lesson (Long 4) - Data

text D_08062634
    .ascii "よくきいてマネしてね。\n"
    .ascii "好きなタイミングでどうぞ。\n"
    .ascii "演奏を止めると、\n"
    .asciz "お手本がきけるヨ！"
endtext


script D_0806268c
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
return


script D_08062770
    spawn_cue CUE_KICK_R
    rest 21
return


text D_08062794
    .ascii "\n"
    .ascii "シンバルとスネアで\n"
    .ascii "キメてみよう！\n"
    .asciz "できるかな？"
endtext


script D_080627c4
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
return


script D_080628c0
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 21
return


text D_080628f0
    .ascii "たったの１つ、音がふえるヨ。\n"
    .ascii "でも　わりと　フクザツな\n"
    .ascii "カンジに　なるんだ！\n"
    .asciz "ついてこれるかな？"
endtext


script D_08062950
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
return


text D_08062a64
    .ascii "\n"
    .ascii "おわりのところを\n"
    .ascii "カッコよくしてみるネ！\n"
    .asciz "がんばってみて！\n"
endtext


script D_08062aa0
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return


text D_08062be4
    .ascii "\n"
    .ascii "アクセントをつけるヨ。\n"
    .ascii "けっこうシブいかも～！\n"
    .asciz "やるしかない！！"
endtext


script D_08062c24
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 12
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return

.end
