.include "include/beatscript.inc"
.include "games/concert_hall/macros.inc"


.section .script.entry
@ Concert Hall - Script Entry Point

glabel script_concert_hall_entry
    set_tempo 124
    rest 24
    rest 24
    load_concert_hall
    enable_play_inputs 1
    assess_inputs 1
    call D_08a603b4
    enable_pause 0
    enable_play_inputs 0
    fade_music_out TO_TEMPO, 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

.end
