.section .rodata

.include "include/beatscript.inc"


@ Prologue (Wizard's Waltz) - Script
glabel script_wizards_waltz_prologue
    set_game_fade_in_time 8
    load_game wizards_waltz_prologue_engine, 0
    run stop_all_soundplayers, 0
    play_sfx s_jingle_witch_seqData
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    run func_08006d80, 0
    rest 24
    set_game_fade_in_time 16
    return

.end
