.include "include/bs_ext.inc"

@ Rhythm Game Engines
.set BON_ODORI,         D_089deff0
.set BOUNCY_ROAD,       D_089e3d78
.set BUNNY_HOP,         D_089e6364
.set CLAPPY_TRIO,       D_089e4778
.set CONCERT_HALL,      D_089e5d0c
.set DRUM_INTRO,        D_089e0378
.set DRUM_LIVE,         D_089e0cc0
.set DRUM_STUDIO,       D_089e2ea0
.set FIREWORKS,         D_089e4500
.set HORSE_MACHINE,     D_089e90b0
.set KARATE_MAN,        D_089df044
.set RHYTHM_TOY,        D_089e9ef0
.set MANNEQUIN_FACTORY, D_089df5f8
.set MARCHING_ORDERS,   D_089e5518
.set METRONOME,         D_089e5948
.set MR_UPBEAT,         D_089e583c
.set NIGHT_WALK,        D_089e382c
.set NINJA_BODYGUARD,   D_089e6b84
.set POLYRHYTHM,        D_089e5be0
.set POWER_CALLIGRAPHY, D_089e4bf8
.set QUIZ_SHOW,         D_089e5ec0
.set RAP_MEN,           D_089e6614
.set RAT_RACE,          D_089e6814
.set RHYTHM_TEST,       D_089e50b8
.set RHYTHM_TWEEZERS,   D_089e41f4
.set SAMURAI_SLICE,     D_089e4908
.set SHOWTIME,          D_089e3aa4
.set SICK_BEATS,        D_089e9330
.set SNEAKY_SPIRITS,    D_089de91c
.set SPACE_DANCE,       D_089e702c
.set SPACEBALL,         D_089deb08
.set STAFF_CREDIT,      D_089df6cc
.set TAP_TRIAL,         D_089e8130
.set TOSS_BOYS,         D_089e8a08
.set TRAM_AND_PAULINE,  D_089e8d7c
.set WIZARDS_WALTZ,     D_089ea068

@ Game Versions
.set VER_0, 0
.set VER_1, 1
.set VER_2, 2
.set VER_3, 3
.set VER_4, 4
.set VER_5, 5
